# Build worker image (VM template)
image: Visual Studio 2015

clone_depth: 5

version: '{build}'

platform:
  - x86

configuration:
  - Release
  #- Debug

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  SW_SDK_SECRET:
    secure: QmzV2W8MxTnxMHKchabCCA==

build:
  verbosity: minimal

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - cmake --version
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

install:
  # SW SDK
  - nuget install secure-file -Version 1.0.31
  - ps: Test-Path C:\projects\csgo-cli\secure-file.1.0.31\tools\secure-file.exe 
  - ps: Test-Path C:\projects\csgo-cli\dependencies\sw_sdk_142.zip.enc
  - C:\projects\csgo-cli\secure-file.1.0.31\tools\secure-file.exe -decrypt C:\projects\csgo-cli\dependencies\sw_sdk_142.zip.enc -secret %SW_SDK_SECRET% -out C:\projects\csgo-cli\dependencies\sw_sdk_142.zip
  - 7z x C:\projects\csgo-cli\dependencies\sw_sdk_142.zip -aoa -y -oC:\projects\csgo-cli\dependencies
  # Google Protobuf
  - curl -fsS --create-dirs -o C:\projects\csgo-cli\downloads\protobuf-cpp-3.5.1.zip https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-cpp-3.5.1.zip
  - 7z x C:\projects\csgo-cli\downloads\protobuf-cpp-3.5.1.zip -aoa -y -oC:\projects\csgo-cli\dependencies
  # output content of dependencies folder, to see if everything is present
  - dir C:\projects\csgo-cli\dependencies\


#build_script:
#after_build:
#artifacts:
#deploy: