# Build worker image (VM template)
image: Visual Studio 2015

clone_depth: 5

version: '{build}'

platform:
  - x86

configuration:
  - Release
  #- Debug

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  SW_SDK_SECRET:
    secure: QmzV2W8MxTnxMHKchabCCA==

build:
  verbosity: minimal

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - cmake --version
  - msbuild /version
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

install:
  # 1) Get Git Submodules: csgo-protobufs
  - git submodule update --init --recursive
  # 2) Secure-File (needed to decrypt steamworks sdk)
  - nuget install secure-file -Version 1.0.31
  - ps: Test-Path C:\projects\csgo-cli\secure-file.1.0.31\tools\secure-file.exe 
  # 3) SteamWorks SDK (prebuild libs + src) 
  - C:\projects\csgo-cli\secure-file.1.0.31\tools\secure-file.exe -decrypt C:\projects\csgo-cli\downloads\sw_sdk_142.zip.enc -secret %SW_SDK_SECRET% -out C:\projects\csgo-cli\downloads\sw_sdk_142.zip
  - 7z x C:\projects\csgo-cli\downloads\sw_sdk_142.zip -aoa -y -oC:\projects\csgo-cli\dependencies
  - cd C:\projects\csgo-cli\dependencies
  - ren sdk sw_sdk
  - cd C:\projects\csgo-cli
  # 4) Google Protobuf (src)
  - ps: Invoke-WebRequest "https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-cpp-3.5.1.zip" -OutFile C:\projects\csgo-cli\downloads\protobuf-cpp-3.5.1.zip
  - 7z x C:\projects\csgo-cli\downloads\protobuf-cpp-3.5.1.zip -aoa -y -oC:\projects\csgo-cli\dependencies
  - cd C:\projects\csgo-cli\dependencies
  - ren protobuf-3.5.1 protobuf   
  - cd C:\projects\csgo-cli
  # 5) MPIR
  - vcpkg install mpir:x64-windows
  - cd C:\Tools\vcpkg\packages
  - ren mpir_x64-windows mpir
  - dir C:\Tools\vcpkg\packages
  - dir C:\Tools\vcpkg\packages\mpir
  - xcopy C:\Tools\vcpkg\packages\mpir C:\projects\csgo-cli\dependencies\mpir /i /y
  # output content of dependencies folder, to see if everything is present
  - dir C:\projects\csgo-cli\downloads\
  - dir C:\projects\csgo-cli\dependencies\
  - dir C:\projects\csgo-cli\dependencies\csgo-protobufs
  


before_build:
  # Build Dependencies
  # 1) Compile Protobuf
  - cd C:\projects\csgo-cli\dependencies\protobuf\cmake
  # 1a) Configure Protobuf
  - cmake -G "Visual Studio 14 2015" -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF
  # 1b) Build Protobuf
  - cmake --build . --config Release --target install
  # 2) Patch CSGO Protobufs
  - C:\projects\csgo-cli\dependencies\csgo-protobufs-patch\patch.bat
  # return
  - cd C:\projects\csgo-cli

build_script:
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - dir C:\projects\csgo-cli
  - msbuild C:\projects\csgo-cli\csgo_cli.sln /m /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 

#after_build:
#artifacts:
#deploy: